/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lenovo_idphoto_nativealgo_detectFaceFeatureClass */

#ifndef _Included_com_lenovo_idphoto_nativealgo_detectFaceFeatureClass
#define _Included_com_lenovo_idphoto_nativealgo_detectFaceFeatureClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lenovo_idphoto_nativealgo_detectFaceFeatureClass
 * Method:    ImageBlur
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_android_ndk_detectFaceFeatureClass_ImageBlur
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
